### PR TITLE
Additional information for file name normalization

### PR DESCRIPTION
**Pull request by llange**
New parameters and mapping to normalize the impots file name.

I left out the renaming of "Formulaire" into "Déclaration", waiting for project confirmation.

Also, I did **not** change '1MEN' from "Primitif" to "PrimitifMensualisé" as it's just an hypothesis of mine, I have no real-world example to confirm it.

Both can be done later after discussion.

---
Nouveaux paramètres et correspondances pour la normalisation du nommage des fichiers impôts.

J'ai mis de côté le renommage de "Formulaire" en "Déclaration", attendant la confirmation de @LucsT pour cela.

Par ailleurs, je n'ai **pas** changé  '1MEN' de "Primitif" à "PrimitifMensualisé" car il s'agit juste d'une hypothèse, je n'ai pas de cas concret pour le vérifier.

Cela peut être fait ultérieurement après discussion.

### CODE REVIEW

**Comment by llange** [comment]
Related to #168

**Comment by LucsT** [comment]
Thank's for the PR. It's a great addition that's we want to add. 
But we will wait a few moment before merging some renaming.
2 reasons why : 
  First, the filename is one of the deduplicating key, if we change name for some files now, there will be duplicate files everywhere. We need to find a better solution before.
  Second, Impots webiste has changed twice last week (login) and due to actual context about 'prélevement à la source', it's probably urge to wait and see.

**Comment by doubleface** [comment]
@llange The new impots website is now used. I think you usecase is not correctly handled. Can you confirm ?

**Comment by llange** [comment]
Hi @doubleface , you're right, I'm closing this PR as the new website does not give that information any more. Thanks.

**Pull request closed without merging**
